INSERT INTO Product(name, description, price) VALUES ("Fromage de chèvres", "Prix de la buchette", 2.5);
INSERT INTO Product(name, description, price) VALUES ("Fromage de brebis", "Prix de la buchette", 3);
INSERT INTO Product(name, description, price) VALUES ("Fromage de vache", "Prix pour 250 grammes", 7.7);
INSERT INTO Product(name, description, price) VALUES ("Lait de vache", "Prix de la brique", 1.19);
INSERT INTO Product(name, description, price) VALUES ("Pomme", "Prix au kg", 4);
INSERT INTO Product(name, description, price) VALUES ("Poire", "Prix au kg", 3.9);
INSERT INTO Product(name, description, price) VALUES ("Orange", "Prix au kg", 3.2);
INSERT INTO Product(name, description, price) VALUES ("Raisin", "Prix au kg", 7.1);
INSERT INTO Product(name, description, price) VALUES ("Fraise", "Prix au kg", 9.68);
INSERT INTO Product(name, description, price) VALUES ("Pamplemousse", "Prix au kg", 3.39);
INSERT INTO Product(name, description, price) VALUES ("Citron", "Prix au kg", 5.6);
INSERT INTO Product(name, description, price) VALUES ("Mandarine", "Prix au kg", 6.4);
INSERT INTO Product(name, description, price) VALUES ("Clémentine", "Prix au kg", 6.2);
INSERT INTO Product(name, description, price) VALUES ("Concombre", "Prix à la pièce", 0.89);
INSERT INTO Product(name, description, price) VALUES ("Courgette", "Prix à la pièce", 0.92);
INSERT INTO Product(name, description, price) VALUES ("Pommes de terre", "Prix au kg", 4);
INSERT INTO Product(name, description, price) VALUES ("Haricot vert", "Prix au kg", 7);
INSERT INTO Product(name, description, price) VALUES ("Chou fleur", "Prix à la pièce", 0.5);
INSERT INTO Product(name, description, price) VALUES ("Salade", "Prix à la pièce", 0.6);
INSERT INTO Product(name, description, price) VALUES ("Petit poi", "Prix au kg", 3.4);
INSERT INTO Product(name, description, price) VALUES ("Carotte", "Prix au kg", 5.2);