INSERT INTO User(producer_id, email, firstname, lastname, password, city, zip_code, street, phone_number) VALUES (1, "frmglande@gmail.com", "Joseph", "Moulin", "root", "Sabres", 40630, "6 Avenue des rouleux", "0999999999");
INSERT INTO User(producer_id, email, firstname, lastname, password, city, zip_code, street, phone_number) VALUES (2, "brebis@gmail.com", "Arnaud", "Langlé", "arnolang", "Bordeaux", 33000, "42 allée des brailels", "0999999999");
INSERT INTO User(producer_id, email, firstname, lastname, password, city, zip_code, street, phone_number) VALUES (3, "frmgbordeaux@gmail.com", "Angèle", "Renaud", "root", "Sabres", 40630, "63 Avenue des peupliers", "0999999999");
INSERT INTO User(producer_id, email, firstname, lastname, password, city, zip_code, street, phone_number) VALUES (4, "vachelaitiere@gmail.com", "Miguel", "Do Santos", "ferrari3000","Bordeaux", 33000, "25 impasse de rené", "0999999999");
INSERT INTO User(producer_id, email, firstname, lastname, password, city, zip_code, street, phone_number) VALUES (5, "pompom@yahoo.com", "Paul", "Boquet", "paul33", "Bordeaux", 33000, "22 allée des cochons sauvages", "0999999999");
INSERT INTO User(producer_id, email, firstname, lastname, password, city, zip_code, street, phone_number) VALUES (6, "arnoval@free.fr", "Arnaud", "Valutier", "ano", "Bordeaux", 33000, "3 allée des coquelicots", "0999999999");
INSERT INTO User(producer_id, email, firstname, lastname, password, city, zip_code, street, phone_number) VALUES (7, "richardupo@hotmail.fr", "Richard", "Dupo", "riri", "Bordeaux", 33000, "8 allée des petits pots", "0999999999");
INSERT INTO User(producer_id, email, firstname, lastname, password, city, zip_code, street, phone_number) VALUES (8, "bigornotBella@outlook.fr", "Bigornot", "Bellamon", "Bella33", "Bordeaux", 33000, "35 allée des souliers", "0999999999");
INSERT INTO User(producer_id, email, firstname, lastname, password, city, zip_code, street, phone_number) VALUES (9, "mariepaul@potier.fr", "Marie-paul", "Sousi", "paupauldu33", "Bordeaux", 33000, "29 avenue des trois cardinots", "0999999999");
INSERT INTO User(producer_id, email, firstname, lastname, password, city, zip_code, street, phone_number) VALUES (10, "giovanni.richemon@gmail.com", "Giovanni", "Richemond", "sachadubourgpalette", "Bordeaux", 33000, "15 impasse des vergers", "0999999999");
INSERT INTO User(producer_id, email, firstname, lastname, password, city, zip_code, street, phone_number) VALUES (11, "josiannedupres@gmail.com", "Josianne", "Duprès", "jojodup", "Bordeaux", 33000, "1 allée des gros pots", "0999999999")